const answer_btn1 = document.querySelector('.answer1')
const answer_btn2 = document.querySelector('.answer2')
const answer_btn3 = document.querySelector('.answer3')
const answer_btn4 = document.querySelector('.answer4')
const A1 = document.querySelector('.A1')
const A2 = document.querySelector('.A2')
const next = document.querySelector('.next')
let number = 1;
start()

function start() {
    A1.innerHTML = '';
    A2.innerHTML = '';
    answer_btn1.disabled = false;
    answer_btn2.disabled = false;
    answer_btn3.disabled = false;
    answer_btn4.disabled = false;
    if (number == 1) {
        document.getElementById('img').src = 'C:\\Users\\jswsa\\OneDrive\\바탕 화면\\Dlab(HTML)\\week9_Quiz\\Flag_Image\\1.Easy\\Korea.png';
        answer_btn1.innerHTML = '한국'
        answer_btn2.innerHTML = '일본'
        answer_btn3.innerHTML = '중국'
        answer_btn4.innerHTML = '미국'
        answer_btn1.addEventListener('click', () => {
            A1.innerHTML = '정답!';
            A2.innerHTML = '한국';
            answer_btn1.disabled = true;
            answer_btn2.disabled = true;
            answer_btn3.disabled = true;
            answer_btn4.disabled = true;
            next.disabled = false;})
        answer_btn2.addEventListener('click', () => {
            A1.innerHTML = '오답!';
            A2.innerHTML = '한국';
            answer_btn1.disabled = true;
            answer_btn2.disabled = true;
            answer_btn3.disabled = true;
            answer_btn4.disabled = true;
            next.disabled = false;})
        answer_btn3.addEventListener('click', () => {
            A1.innerHTML = '오답!';
            A2.innerHTML = '한국';
            answer_btn1.disabled = true;
            answer_btn2.disabled = true;
            answer_btn3.disabled = true;
            answer_btn4.disabled = true;
            next.disabled = false;})
        answer_btn4.addEventListener('click', () => {
            A1.innerHTML = '오답!';
            A2.innerHTML = '한국';
            answer_btn1.disabled = true;
            answer_btn2.disabled = true;
            answer_btn3.disabled = true;
            answer_btn4.disabled = true;
            next.disabled = false;})}
    else if (number == 2) {
        document.getElementById('img').src = 'C:\\Users\\jswsa\\OneDrive\\바탕 화면\\Dlab(HTML)\\week9_Quiz\\Flag_Image\\1.Easy\\Japan.png';
        answer_btn1.innerHTML = '중국'
        answer_btn2.innerHTML = '영국'
        answer_btn3.innerHTML = '일본'
        answer_btn4.innerHTML = '프랑스'
        answer_btn1.addEventListener('click', () => {
            A1.innerHTML = '오답!';
            A2.innerHTML = '일본';
            answer_btn1.disabled = true;
            answer_btn2.disabled = true;
            answer_btn3.disabled = true;
            answer_btn4.disabled = true;
            next.disabled = false;})
        answer_btn2.addEventListener('click', () => {
            A1.innerHTML = '오답!';
            A2.innerHTML = '일본';
            answer_btn1.disabled = true;
            answer_btn2.disabled = true;
            answer_btn3.disabled = true;
            answer_btn4.disabled = true;
            next.disabled = false;})
        answer_btn3.addEventListener('click', () => {
            A1.innerHTML = '정답!';
            A2.innerHTML = '일본';
            answer_btn1.disabled = true;
            answer_btn2.disabled = true;
            answer_btn3.disabled = true;
            answer_btn4.disabled = true;
            next.disabled = false;})
        answer_btn4.addEventListener('click', () => {
            A1.innerHTML = '오답!';
            A2.innerHTML = '일본';
            answer_btn1.disabled = true;
            answer_btn2.disabled = true;
            answer_btn3.disabled = true;
            answer_btn4.disabled = true;
            next.disabled = false;})}
    else if (number == 3) {
        document.getElementById('img').src = 'C:\\Users\\jswsa\\OneDrive\\바탕 화면\\Dlab(HTML)\\week9_Quiz\\Flag_Image\\1.Easy\\China.png';
        answer_btn1.innerHTML = '중국'
        answer_btn2.innerHTML = '베트남'
        answer_btn3.innerHTML = '멕시코'
        answer_btn4.innerHTML = '미국'
        answer_btn1.addEventListener('click', () => {
            A1.innerHTML = '정답!';
            A2.innerHTML = '중국';
            answer_btn1.disabled = true;
            answer_btn2.disabled = true;
            answer_btn3.disabled = true;
            answer_btn4.disabled = true;
            next.disabled = false;})
        answer_btn2.addEventListener('click', () => {
            A1.innerHTML = '오답!';
            A2.innerHTML = '중국';
            answer_btn1.disabled = true;
            answer_btn2.disabled = true;
            answer_btn3.disabled = true;
            answer_btn4.disabled = true;
            next.disabled = false;})
        answer_btn3.addEventListener('click', () => {
            A1.innerHTML = '오답!';
            A2.innerHTML = '중국';
            answer_btn1.disabled = true;
            answer_btn2.disabled = true;
            answer_btn3.disabled = true;
            answer_btn4.disabled = true;
            next.disabled = false;})
        answer_btn4.addEventListener('click', () => {
            A1.innerHTML = '오답!';
            A2.innerHTML = '중국';
            answer_btn1.disabled = true;
            answer_btn2.disabled = true;
            answer_btn3.disabled = true;
            answer_btn4.disabled = true;
            next.disabled = false;})}
    else if (number == 4) {
        document.getElementById('img').src = 'C:\\Users\\jswsa\\OneDrive\\바탕 화면\\Dlab(HTML)\\week9_Quiz\\Flag_Image\\1.Easy\\USA.png';
        answer_btn1.innerHTML = '영국'
        answer_btn2.innerHTML = '대만'
        answer_btn3.innerHTML = '미국'
        answer_btn4.innerHTML = '한국'
        answer_btn1.addEventListener('click', () => {
            A1.innerHTML = '오답!';
            A2.innerHTML = '미국';
            answer_btn1.disabled = true;
            answer_btn2.disabled = true;
            answer_btn3.disabled = true;
            answer_btn4.disabled = true;
            next.disabled = false;})
        answer_btn2.addEventListener('click', () => {
            A1.innerHTML = '오답!';
            A2.innerHTML = '미국';
            answer_btn1.disabled = true;
            answer_btn2.disabled = true;
            answer_btn3.disabled = true;
            answer_btn4.disabled = true;
            next.disabled = false;})
        answer_btn3.addEventListener('click', () => {
            A1.innerHTML = '정답!';
            A2.innerHTML = '미국';
            answer_btn1.disabled = true;
            answer_btn2.disabled = true;
            answer_btn3.disabled = true;
            answer_btn4.disabled = true;
            next.disabled = false;})
        answer_btn4.addEventListener('click', () => {
            A1.innerHTML = '오답!';
            A2.innerHTML = '미국';
            answer_btn1.disabled = true;
            answer_btn2.disabled = true;
            answer_btn3.disabled = true;
            answer_btn4.disabled = true;
            next.disabled = false;})}
    else if (number == 5) {
        document.getElementById('img').src = 'C:\\Users\\jswsa\\OneDrive\\바탕 화면\\Dlab(HTML)\\week9_Quiz\\Flag_Image\\2.Normal\\Egypt.png';
        answer_btn1.innerHTML = '오스트리아'
        answer_btn2.innerHTML = '이집트'
        answer_btn3.innerHTML = '가나'
        answer_btn4.innerHTML = '아르헨티나'
        answer_btn1.addEventListener('click', () => {
            A1.innerHTML = '오답!';
            A2.innerHTML = '이집트';
            answer_btn1.disabled = true;
            answer_btn2.disabled = true;
            answer_btn3.disabled = true;
            answer_btn4.disabled = true;
            next.disabled = false;})
        answer_btn2.addEventListener('click', () => {
            A1.innerHTML = '정답!';
            A2.innerHTML = '이집트';
            answer_btn1.disabled = true;
            answer_btn2.disabled = true;
            answer_btn3.disabled = true;
            answer_btn4.disabled = true;
            next.disabled = false;})
        answer_btn3.addEventListener('click', () => {
            A1.innerHTML = '오답!';
            A2.innerHTML = '이집트';
            answer_btn1.disabled = true;
            answer_btn2.disabled = true;
            answer_btn3.disabled = true;
            answer_btn4.disabled = true;
            next.disabled = false;})
        answer_btn4.addEventListener('click', () => {
            A1.innerHTML = '오답!';
            A2.innerHTML = '이집트';
            answer_btn1.disabled = true;
            answer_btn2.disabled = true;
            answer_btn3.disabled = true;
            answer_btn4.disabled = true;
            next.disabled = false;})}
        next.onclick = () => {
            next.disabled = true;
            number++;
            console.log(number)
            start()
        }
}